import java.util.InputMismatchException;
import java.util.Random;
import java.util.Scanner;

public class Game {


    public static void main(String[] args) {
        Game.startGame();
    }

    public static int startGame() {
        Scanner scanner = new Scanner(System.in);

        //start game
        System.out.println("Welcome to Rock | Paper | Scissors");

        System.out.println(getCPUResponse());


        //create a variable to hold the user reponse using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)
        boolean notValid = true;

        int choice;

        while (notValid) {
            System.out.println("Please Select an Integer Choice - 1. Rock 2. Paper 3. Scissor");
            try {
                choice = scanner.nextInt();
            } catch (InputMismatchException ex) {
                notValid = true;
            }
            notValid = false;
        }

        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        int cpuResponse = getCPUResponse();
        //compare user and cpu response with each other to decide the winner.

        Scissors scissors = new Scissors(cpuResponse);

        Rock rock = new Rock(cpuResponse);

        Paper paper = new Paper(cpuResponse);

        System.out.println(scissors.checkOutcome());


        return getCPUResponse();
    }

    public static int getCPUResponse() {
        // Generate random integers in range 1 to 3

        Random random = new Random();

        return random.nextInt(3) + 1;
    }
}













